const SONGS = [
  {
    id: 1,
    title: "Midnight Dreams",
    artist: "Luna Wave",
    album: "Dreamscape",
    duration: 214,
    cover: "https://images.pexels.com/photos/3721941/pexels-photo-3721941.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    genre: "Electronic",
  },
  {
    id: 2,
    title: "Ocean Breeze",
    artist: "Coral Reef",
    album: "Tidal",
    duration: 248,
    cover: "https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    genre: "Ambient",
  },
  {
    id: 3,
    title: "Neon Lights",
    artist: "Circuit Beat",
    album: "Synthetic",
    duration: 195,
    cover: "https://images.pexels.com/photos/154147/pexels-photo-154147.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    genre: "Synthwave",
  },
  {
    id: 4,
    title: "Golden Hour",
    artist: "Solara",
    album: "Radiance",
    duration: 232,
    cover: "https://images.pexels.com/photos/1435075/pexels-photo-1435075.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    genre: "Pop",
  },
  {
    id: 5,
    title: "Deep Focus",
    artist: "Neurosis",
    album: "Clarity",
    duration: 267,
    cover: "https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    genre: "Lo-fi",
  },
  {
    id: 6,
    title: "Electric Pulse",
    artist: "Voltage",
    album: "Current",
    duration: 188,
    cover: "https://images.pexels.com/photos/114820/pexels-photo-114820.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    genre: "Electronic",
  },
  {
    id: 7,
    title: "Velvet Sky",
    artist: "Aurora",
    album: "Celestial",
    duration: 301,
    cover: "https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    genre: "Ambient",
  },
  {
    id: 8,
    title: "Rhythm & Soul",
    artist: "Groove Collective",
    album: "Funk Fusion",
    duration: 256,
    cover: "https://images.pexels.com/photos/210922/pexels-photo-210922.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    genre: "Funk",
  },
  {
    id: 9,
    title: "Starlight",
    artist: "Cosmic Drift",
    album: "Nebula",
    duration: 223,
    cover: "https://images.pexels.com/photos/956999/milky-way-starry-sky-night-sky-star-956999.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    genre: "Ambient",
  },
  {
    id: 10,
    title: "Urban Flow",
    artist: "Street Beats",
    album: "Metro",
    duration: 199,
    cover: "https://images.pexels.com/photos/3394655/pexels-photo-3394655.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    genre: "Hip-hop",
  },
  {
    id: 11,
    title: "Crystal Clear",
    artist: "Pure Wave",
    album: "Transparent",
    duration: 241,
    cover: "https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    genre: "Electronic",
  },
  {
    id: 12,
    title: "Sunset Drive",
    artist: "Coastal",
    album: "Highway",
    duration: 278,
    cover: "https://images.pexels.com/photos/2387878/pexels-photo-2387878.jpeg?auto=compress&cs=tinysrgb&w=400",
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    genre: "Rock",
  },
];

const ARTISTS = [
  {
    id: 1,
    name: "Luna Wave",
    image: "https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=400",
    genre: "Electronic",
  },
  {
    id: 2,
    name: "Coral Reef",
    image: "https://images.pexels.com/photos/3785077/pexels-photo-3785077.jpeg?auto=compress&cs=tinysrgb&w=400",
    genre: "Ambient",
  },
  {
    id: 3,
    name: "Circuit Beat",
    image: "https://images.pexels.com/photos/3721941/pexels-photo-3721941.jpeg?auto=compress&cs=tinysrgb&w=400",
    genre: "Synthwave",
  },
  {
    id: 4,
    name: "Solara",
    image: "https://images.pexels.com/photos/1060955/pexels-photo-1060955.jpeg?auto=compress&cs=tinysrgb&w=400",
    genre: "Pop",
  },
  {
    id: 5,
    name: "Aurora",
    image: "https://images.pexels.com/photos/1037913/pexels-photo-1037913.jpeg?auto=compress&cs=tinysrgb&w=400",
    genre: "Ambient",
  },
];

const ALBUMS = [
  {
    id: 1,
    title: "Dreamscape",
    artist: "Luna Wave",
    year: 2024,
    cover: "https://images.pexels.com/photos/3721941/pexels-photo-3721941.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    id: 2,
    title: "Tidal",
    artist: "Coral Reef",
    year: 2024,
    cover: "https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    id: 3,
    title: "Synthetic",
    artist: "Circuit Beat",
    year: 2023,
    cover: "https://images.pexels.com/photos/154147/pexels-photo-154147.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    id: 4,
    title: "Radiance",
    artist: "Solara",
    year: 2024,
    cover: "https://images.pexels.com/photos/1435075/pexels-photo-1435075.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    id: 5,
    title: "Celestial",
    artist: "Aurora",
    year: 2023,
    cover: "https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    id: 6,
    title: "Funk Fusion",
    artist: "Groove Collective",
    year: 2024,
    cover: "https://images.pexels.com/photos/210922/pexels-photo-210922.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
];
